name : Graded Project Action

on:
  push:
    branches: [main]

jobs:
  run-flask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
    - run: pip install -r requirements.txt
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: deepak2132/gradedproject
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_USERNAME}}
